--Script Modulo Login(Seguridad) Facturación Electronica POS
CREATE TABLE SEC_USER(
	ID INT IDENTITY(1,1) NOT NULL,
	NAME NVARCHAR(50) NOT NULL,
	LASTNAME NVARCHAR(100) NOT NULL,
	DOCUMENT NVARCHAR(30) NOT NULL UNIQUE,
	CELLPHONE NVARCHAR(30),
	CITY NVARCHAR(50),
	EMAIL NVARCHAR(100) NOT NULL,
	USER_PASSWORD NVARCHAR(100) NOT NULL,
	REMOVED BIT,
	REMOVED_DATE DATETIME,
	CREATE_DATE DATETIME,
	UPDATE_DATE DATETIME,
	REMOVE_USER_ID INT,
	CREATE_USER_ID INT,
	UPDATE_USER_ID INT,
	CONSTRAINT ID_SEC_USER_PK PRIMARY KEY(ID)
);

CREATE TABLE SEC_ROLE(
	ID INT IDENTITY(1,1) NOT NULL,
	NAME NVARCHAR(50) NOT NULL,
	REMOVED BIT,
	DESCRIPT NVARCHAR(100),
	CONSTRAINT ID_SEC_ROLE_PK PRIMARY KEY(ID)
);

CREATE TABLE SEC_SESSION(
	ID BIGINT IDENTITY(1,1) NOT NULL,
	USERID INT NOT NULL,
	LOGIN_DATE DATETIME NOT NULL,
	IP_ADDRESS NVARCHAR(40) NOT NULL,
	TOKEN NVARCHAR(100) NOT NULL,
	TOKEN_STATUS BIT NOT NULL DEFAULT 1,
	CONSTRAINT ID_SEC_SESSION_PK PRIMARY KEY(ID),
	CONSTRAINT ID_USER_SESSION_FK FOREIGN KEY(USERID) REFERENCES SEC_USER(ID)
);

CREATE TABLE SEC_USER_ROLE(
	ID INT IDENTITY(1,1) NOT NULL,
	USERID INT NOT NULL,
	ROLEID INT NOT NULL,
	CONSTRAINT ID_SEC_SEC_USER_ROLE_PK PRIMARY KEY(ID),
	CONSTRAINT ID_USER_SEC_USER_ROLE_FK FOREIGN KEY(USERID) REFERENCES SEC_USER(ID),
	CONSTRAINT ID_ROLE_SEC_USER_ROLE_FK FOREIGN KEY(ROLEID) REFERENCES SEC_ROLE(ID),
	UNIQUE(USERID, ROLEID)
);

--Insert Usuario de pruebas
INSERT INTO SEC_USER VALUES('STIVEN', 'VELEZ', 111111,NULL, NULL,'stivenvelezbedoy@gmail.com',
'21jejAlo',NULL,NULL,NULL,NULL,NULL,NULL,NULL);
SELECT * FROM SEC_USER